"""Systematic robustness evaluation under simulated capture conditions.

Usage:  python tests/evaluate.py [--seeds N] [--out research/04_evaluation_results.md]

For every colour profile x EC level x capture preset we encode random payloads
(version 6 symbols, 41x41 modules), run them through the camera simulator with
several random seeds and record the decode success rate and the mean module
error rate.  The density column is net payload bits per module (after the
container header and RS parity) so that profiles can be compared on an equal
footing: what matters is  density x success.
"""
import argparse, os, sys, time
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np

from cqr import codec, render, layout
from cqr.decoder import decode_image
from cqr.profiles import PROFILES, EC_LEVELS
from cqr.simulate import CameraParams, simulate

PRESETS = {
    "screen":     CameraParams(module_px=8.0, rotation_deg=3, tilt=0.03, blur_sigma=0.4, noise_sigma=0.01,
                               jpeg_quality=90),
    "scanner":    CameraParams(module_px=6.0, rotation_deg=1, tilt=0.0, blur_sigma=0.7, noise_sigma=0.015,
                               color_cast=(1.02, 1.0, 0.95), gamma=1.1, black_level=0.05, white_level=0.95,
                               crosstalk=0.06),
    "phone-good": CameraParams(module_px=6.0, rotation_deg=10, tilt=0.12, blur_sigma=0.8, noise_sigma=0.025,
                               color_cast=(1.08, 1.0, 0.85), gamma=1.2, black_level=0.10, white_level=0.90,
                               crosstalk=0.08, jpeg_quality=85),
    "phone-poor": CameraParams(module_px=4.5, rotation_deg=20, tilt=0.2, blur_sigma=1.0, noise_sigma=0.04,
                               color_cast=(1.1, 0.95, 0.75), gamma=1.3, black_level=0.15, white_level=0.85,
                               crosstalk=0.12, jpeg_quality=70),
}
VERSION = 6


def run(seeds: int, out_path: str, profiles=None, ec_levels=None):
    profiles = profiles or [p.name for p in PROFILES.values()]
    ec_levels = ec_levels or list(EC_LEVELS)
    rng = np.random.default_rng(123)
    rows = []
    t0 = time.time()
    size = layout.size_for_version(VERSION)
    for prof in profiles:
        for ec in ec_levels:
            cap = codec.capacity(VERSION, ec, prof)
            bpm_net = cap * 8 / size ** 2
            for preset_name, base in PRESETS.items():
                ok = 0
                errs = []
                for s in range(seeds):
                    payload = bytes(rng.integers(0, 256, cap, dtype=np.uint8))
                    sym = codec.encode(payload, ec_level=ec, profile=prof, version=VERSION)
                    img = render.to_array(sym, module_px=8)
                    p = CameraParams(**{**base.__dict__, "seed": s, "rotation_deg": base.rotation_deg + s * 7})
                    cam = simulate(img, p)
                    try:
                        rep = decode_image(cam, return_report=True)
                        good = rep.result.ok and rep.result.data == payload
                        err = float((rep.levels != sym.levels).any(axis=1).mean())
                    except Exception:
                        good, err = False, float("nan")
                    ok += good
                    errs.append(err)
                rows.append((prof, ec, preset_name, cap, bpm_net, ok / seeds, float(np.nanmean(errs)) if not all(np.isnan(errs)) else float("nan")))
                print(f"{prof:7s} {ec} {preset_name:10s} cap {cap:5d} B  net {bpm_net:5.2f} b/mod  success {ok}/{seeds}  "
                      f"module err {rows[-1][-1]:.3f}", flush=True)
    elapsed = time.time() - t0
    lines = ["# Evaluation results (simulated capture)", "",
             f"Generated by `tests/evaluate.py` with {seeds} seeds per cell, version {VERSION} symbols "
             f"({size}x{size} modules), {elapsed:.0f} s total.", "",
             "Presets (see `cqr/simulate.py` and `tests/evaluate.py` for the exact parameters):", ""]
    for name, p in PRESETS.items():
        lines.append(f"- **{name}**: {p.module_px} px/module, tilt {p.tilt}, blur sigma {p.blur_sigma} px, noise {p.noise_sigma}, "
                     f"colour cast {p.color_cast}, gamma {p.gamma}, black/white level {p.black_level}/{p.white_level}, "
                     f"cross-talk {p.crosstalk}, JPEG {p.jpeg_quality}")
    lines += ["", "`net b/mod` = payload bits per module after header and RS parity; `success` = fraction of symbols decoded "
              "bit-exact; `mod err` = mean fraction of data modules misclassified before error correction.", ""]
    lines += ["| profile | EC | preset | payload B | net b/mod | success | mod err |", "|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]:.2f} | {r[5]:.0%} | {r[6]:.3f} |")
    # summary: best net density per preset with 100% success
    lines += ["", "## Best profile per preset (highest net density with 100 % success)", "",
              "| preset | profile | EC | net b/mod | gain vs mono/L |", "|---|---|---|---|---|"]
    mono = {r[2]: r[4] for r in rows if r[0] == "mono" and r[1] == "L"}
    for preset in PRESETS:
        good = [r for r in rows if r[2] == preset and r[5] >= 1.0]
        if good:
            best = max(good, key=lambda r: r[4])
            base = mono.get(preset, float("nan"))
            lines.append(f"| {preset} | {best[0]} | {best[1]} | {best[4]:.2f} | {best[4] / base:.2f}x |")
        else:
            lines.append(f"| {preset} | - | - | - | - |")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", out_path)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, default=5)
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "research", "04_evaluation_results.md"))
    ap.add_argument("--profiles", nargs="*", default=None)
    ap.add_argument("--ec", nargs="*", default=None)
    a = ap.parse_args()
    run(a.seeds, a.out, a.profiles, a.ec)
