"""Generate an A4 test page of CQR symbols for printing and photographing.

Output (in print_test/):
  cqr_print_test_A4.pdf / .png  - 300 dpi A4 page, print at 100 % scale (no "fit to page")
  manifest.json                 - id -> payload, profile, EC level, version, module size

Grid: rows = colour profiles, columns = module sizes (1.0 / 0.7 / 0.5 mm).
All symbols are version 3 (29x29 modules), EC level M, 2-module quiet zone,
spaced widely so that a photo of the whole page can be cropped per symbol.
"""
import json, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from PIL import Image, ImageDraw, ImageFont
from cqr import codec, render

DPI = 300
MM = DPI / 25.4
PAGE = (int(round(210 * MM)), int(round(297 * MM)))   # A4 portrait
VERSION = 3
EC = "M"
QUIET = 2
PROFILES = ["mono", "rgb111", "rgb221", "rgb222", "rgb332", "rgb333"]
MODULE_PX = [12, 8, 6]                                  # 1.02 / 0.68 / 0.51 mm at 300 dpi
OUT = os.path.join(os.path.dirname(__file__), "..", "print_test")


def font(size):
    try:
        return ImageFont.truetype("arial.ttf", size)
    except OSError:
        return ImageFont.load_default(size=size)


def main():
    os.makedirs(OUT, exist_ok=True)
    page = Image.new("RGB", PAGE, "white")
    draw = ImageDraw.Draw(page)
    f_title, f_text, f_label = font(60), font(34), font(30)
    margin = int(12 * MM)
    y = margin
    draw.text((margin, y), "CQR colour QR code - print test page", fill="black", font=f_title)
    y += 75
    draw.text((margin, y), "Print at 100 % scale on white paper (no 'fit to page'). Photograph straight on, in even daylight,",
              fill="black", font=f_text)
    y += 42
    draw.text((margin, y), "sharp focus, no flash; one symbol per photo or the whole page. Rows: colour profile, columns: module size.",
              fill="black", font=f_text)
    y += 42
    draw.text((margin, y), f"All symbols: version {VERSION} (29x29 modules), EC level {EC}, 300 dpi.  Generated by tests/make_print_page.py",
              fill="black", font=f_text)
    y += 70

    manifest = {}
    col_w = (PAGE[0] - 2 * margin) // len(MODULE_PX)
    row_h = (PAGE[1] - y - margin) // len(PROFILES)
    for r, prof in enumerate(PROFILES):
        for c, mpx in enumerate(MODULE_PX):
            sid = f"{chr(65 + r)}{c + 1}"
            mm = mpx / MM
            text = f"CQR print test {sid}: profile {prof}, EC {EC}, module {mm:.2f} mm. "
            cap = codec.capacity(VERSION, EC, prof)
            filler = "The quick brown fox jumps over the lazy dog. 0123456789 "
            payload = text
            while len((payload + filler).encode()) <= cap * 0.9:
                payload += filler
            if len(payload.encode()) > cap:
                payload = text[:cap]
            sym = codec.encode(payload, ec_level=EC, profile=prof, version=VERSION)
            img = render.to_image(sym, module_px=mpx, quiet=QUIET)
            x0 = margin + c * col_w + (col_w - img.width) // 2
            y0 = y + r * row_h + (row_h - 45 - img.height) // 2
            page.paste(img, (x0, y0))
            label = f"{sid}  {prof}  {mm:.2f} mm/module  {sym.payload_bytes} B"
            tw = draw.textlength(label, font=f_label)
            draw.text((margin + c * col_w + (col_w - tw) / 2, y + r * row_h + row_h - 42), label, fill="black", font=f_label)
            manifest[sid] = {"payload": payload, "profile": prof, "ec": EC, "version": VERSION,
                             "module_px_300dpi": mpx, "module_mm": round(mm, 3), "quiet_zone": QUIET,
                             "bits_per_module": sym.profile.bits_per_module, "payload_bytes": sym.payload_bytes,
                             "bbox_px": [x0, y0, x0 + img.width, y0 + img.height],
                             "bbox_mm": [round(v / MM, 1) for v in (x0, y0, x0 + img.width, y0 + img.height)]}
    page.save(os.path.join(OUT, "cqr_print_test_A4.png"), dpi=(DPI, DPI))
    page.save(os.path.join(OUT, "cqr_print_test_A4.pdf"), resolution=DPI)
    with open(os.path.join(OUT, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
    print("wrote", OUT, "with", len(manifest), "symbols")


if __name__ == "__main__":
    main()
